VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsAbsRcdSlctForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Class")
Option Compare Database
Option Explicit

'**************************
'*レコード選択フォーム処理クラス　インタフェース
'**************************

'定数欄

'変数欄



'******************************************************************************************
'*getter/setter欄
'******************************************************************************************




Public Function getInfo(ByRef pDicInfo As Object) As Boolean

End Function

Public Function btnOKClick(ByVal pForm As Object) As Boolean

End Function
