VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsAbsRegiOrEditForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Class")
Option Compare Database
Option Explicit

'**************************
'*登録or編集Form処理クラス　インタフェース
'**************************

'定数欄

'変数欄



'******************************************************************************************
'*getter/setter欄
'******************************************************************************************




Public Function getInfo(ByRef pDicInfo As Object) As Boolean

End Function

Public Function getPreviousFormData(ByRef currentID As Long) As Boolean

End Function

Public Function btnExecuteClick(ByRef Cancel As Boolean) As Boolean

End Function
